Consolidate local wp-cli commands for easy use

diff --git a/bin/prep_local_db b/bin/prep_local_db
--- a/bin/prep_local_db
+++ b/bin/prep_local_db
@@ -14,6 +14,11 @@ if [[ ! $2 =~ $re ]]; then
   echo "Local site ID is not a number" >&2; exit 1
 fi
 
+if ! test $(which wp)
+then
+  echo "WP-CLI is required." >&2; exit 1
+fi
+
 if [[ -f 'pull_plugins' ]]; then
   LOCAL_DB='../www/'
 elif [[ -f 'Vagrantfile' ]]; then
@@ -23,11 +28,15 @@ else
   exit
 fi
 
-sed -i.bak s/wp_$1_/wp_$2_/g $LOCAL_DB$3
+wp @wsuwp db export $3.sql --tables=$(wp @wsuwp db tables --url=$3 --scope=blog --format=csv)
+scp wsuwp-prod-01:$3.sql $LOCAL_DB
 
-if test $(which wp)
-then
-  wp @local db import /var/www/$3
-else
-  echo "WP-CLI not found, import database manually."
-fi
+sed -i.bak s/wp_$1_/wp_$2_/g $LOCAL_DB$3.sql
+echo "Replaced wp_$1 with wp_$2 in $3.sql"
+
+wp @local db import /var/www/$3.sql
+
+wp @local search-replace "$3" "$4" --url=$4
+wp @local search-replace "https://$4" "http://$4" --url=$4
+wp @local search-replace "sites/$1/" "sites/$2/" --url=$4
+wp @local cache flush
